baseURL = 'https://2022.nwerc.eu/'
copyright = "W.I.S.V. `Christiaan Huygens'"
languageCode = 'en-us'
title = 'NWERC 2022'
theme = "ananke"


[params]
  favicon = ""
  site_logo = "nwerc-website.svg"
  background_color_class = "bg-navy"
  custom_css = ["background.css", "schedule.css", "tables.css"]
  mainSections = ['news']
  env = "production"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
