baseURL = 'https://2022.nwerc.eu/'
copyright = "W.I.S.V. `Christiaan Huygens'"
languageCode = 'en-us'
title = 'NWERC 2022'
theme = "ananke"
[params]
  site_logo = "nwerc-website.svg"
  custom_css = ["schedule.css"]
  mainSections = ['news']